# ===================================================================
# Spring Boot configuration for the "secret-samples" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Samples for required secrets to be used in development and ci using prod profile.
# ===================================================================

spring:

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: Yjg3NTM3NTY2MGQ3NTAwNzU5ZGM1NDkyMTFhYmU4NzE5M2YzYmY1YWJjMjQ3NWFjOTNhNTUxNzRmNTVmN2M4YjVkMWNjYmU1Nzc5MmU5OWRmNDQ5MjRiMjgxZWQ3ZGE3NTc5ZDVjMzBjNTU3M2IzMGUyNmQ0NWJiZTg2ZTQyNWM=
