package com.vht.ems.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AlertRuleAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlertRuleAllPropertiesEquals(AlertRule expected, AlertRule actual) {
        assertAlertRuleAutoGeneratedPropertiesEquals(expected, actual);
        assertAlertRuleAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlertRuleAllUpdatablePropertiesEquals(AlertRule expected, AlertRule actual) {
        assertAlertRuleUpdatableFieldsEquals(expected, actual);
        assertAlertRuleUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlertRuleAutoGeneratedPropertiesEquals(AlertRule expected, AlertRule actual) {
        assertThat(actual)
            .as("Verify AlertRule auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlertRuleUpdatableFieldsEquals(AlertRule expected, AlertRule actual) {
        assertThat(actual)
            .as("Verify AlertRule relevant properties")
            .satisfies(a -> assertThat(a.getMetricType()).as("check metricType").isEqualTo(expected.getMetricType()))
            .satisfies(a -> assertThat(a.getThresholdWarning()).as("check thresholdWarning").isEqualTo(expected.getThresholdWarning()))
            .satisfies(a -> assertThat(a.getThresholdCritical()).as("check thresholdCritical").isEqualTo(expected.getThresholdCritical()))
            .satisfies(a -> assertThat(a.getEnabled()).as("check enabled").isEqualTo(expected.getEnabled()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlertRuleUpdatableRelationshipsEquals(AlertRule expected, AlertRule actual) {
        // empty method
    }
}
