package com.vht.ems.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AlertEventAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlertEventAllPropertiesEquals(AlertEvent expected, AlertEvent actual) {
        assertAlertEventAutoGeneratedPropertiesEquals(expected, actual);
        assertAlertEventAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlertEventAllUpdatablePropertiesEquals(AlertEvent expected, AlertEvent actual) {
        assertAlertEventUpdatableFieldsEquals(expected, actual);
        assertAlertEventUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlertEventAutoGeneratedPropertiesEquals(AlertEvent expected, AlertEvent actual) {
        assertThat(actual)
            .as("Verify AlertEvent auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlertEventUpdatableFieldsEquals(AlertEvent expected, AlertEvent actual) {
        assertThat(actual)
            .as("Verify AlertEvent relevant properties")
            .satisfies(a -> assertThat(a.getMetricType()).as("check metricType").isEqualTo(expected.getMetricType()))
            .satisfies(a -> assertThat(a.getValue()).as("check value").isEqualTo(expected.getValue()))
            .satisfies(a -> assertThat(a.getSeverity()).as("check severity").isEqualTo(expected.getSeverity()))
            .satisfies(a -> assertThat(a.getMessage()).as("check message").isEqualTo(expected.getMessage()))
            .satisfies(a -> assertThat(a.getTriggeredAt()).as("check triggeredAt").isEqualTo(expected.getTriggeredAt()))
            .satisfies(a -> assertThat(a.getResolvedAt()).as("check resolvedAt").isEqualTo(expected.getResolvedAt()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlertEventUpdatableRelationshipsEquals(AlertEvent expected, AlertEvent actual) {
        assertThat(actual)
            .as("Verify AlertEvent relationships")
            .satisfies(a -> assertThat(a.getDevice()).as("check device").isEqualTo(expected.getDevice()))
            .satisfies(a -> assertThat(a.getRule()).as("check rule").isEqualTo(expected.getRule()));
    }
}
