package com.vht.ems.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CredentialAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCredentialAllPropertiesEquals(Credential expected, Credential actual) {
        assertCredentialAutoGeneratedPropertiesEquals(expected, actual);
        assertCredentialAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCredentialAllUpdatablePropertiesEquals(Credential expected, Credential actual) {
        assertCredentialUpdatableFieldsEquals(expected, actual);
        assertCredentialUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCredentialAutoGeneratedPropertiesEquals(Credential expected, Credential actual) {
        assertThat(actual)
            .as("Verify Credential auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCredentialUpdatableFieldsEquals(Credential expected, Credential actual) {
        assertThat(actual)
            .as("Verify Credential relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getAuthType()).as("check authType").isEqualTo(expected.getAuthType()))
            .satisfies(a -> assertThat(a.getUsername()).as("check username").isEqualTo(expected.getUsername()))
            .satisfies(a -> assertThat(a.getEncryptedSecret()).as("check encryptedSecret").isEqualTo(expected.getEncryptedSecret()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCredentialUpdatableRelationshipsEquals(Credential expected, Credential actual) {
        // empty method
    }
}
