package com.vht.ems.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MetricSampleAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMetricSampleAllPropertiesEquals(MetricSample expected, MetricSample actual) {
        assertMetricSampleAutoGeneratedPropertiesEquals(expected, actual);
        assertMetricSampleAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMetricSampleAllUpdatablePropertiesEquals(MetricSample expected, MetricSample actual) {
        assertMetricSampleUpdatableFieldsEquals(expected, actual);
        assertMetricSampleUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMetricSampleAutoGeneratedPropertiesEquals(MetricSample expected, MetricSample actual) {
        assertThat(actual)
            .as("Verify MetricSample auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMetricSampleUpdatableFieldsEquals(MetricSample expected, MetricSample actual) {
        assertThat(actual)
            .as("Verify MetricSample relevant properties")
            .satisfies(a -> assertThat(a.getCpuUsage()).as("check cpuUsage").isEqualTo(expected.getCpuUsage()))
            .satisfies(a -> assertThat(a.getRamUsage()).as("check ramUsage").isEqualTo(expected.getRamUsage()))
            .satisfies(a -> assertThat(a.getDiskUsage()).as("check diskUsage").isEqualTo(expected.getDiskUsage()))
            .satisfies(a -> assertThat(a.getPingLatencyMs()).as("check pingLatencyMs").isEqualTo(expected.getPingLatencyMs()))
            .satisfies(a -> assertThat(a.getCollectedAt()).as("check collectedAt").isEqualTo(expected.getCollectedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMetricSampleUpdatableRelationshipsEquals(MetricSample expected, MetricSample actual) {
        assertThat(actual)
            .as("Verify MetricSample relationships")
            .satisfies(a -> assertThat(a.getDevice()).as("check device").isEqualTo(expected.getDevice()));
    }
}
