package com.vht.ems.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TopologyLinkAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTopologyLinkAllPropertiesEquals(TopologyLink expected, TopologyLink actual) {
        assertTopologyLinkAutoGeneratedPropertiesEquals(expected, actual);
        assertTopologyLinkAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTopologyLinkAllUpdatablePropertiesEquals(TopologyLink expected, TopologyLink actual) {
        assertTopologyLinkUpdatableFieldsEquals(expected, actual);
        assertTopologyLinkUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTopologyLinkAutoGeneratedPropertiesEquals(TopologyLink expected, TopologyLink actual) {
        assertThat(actual)
            .as("Verify TopologyLink auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTopologyLinkUpdatableFieldsEquals(TopologyLink expected, TopologyLink actual) {
        assertThat(actual)
            .as("Verify TopologyLink relevant properties")
            .satisfies(a -> assertThat(a.getLinkType()).as("check linkType").isEqualTo(expected.getLinkType()))
            .satisfies(a -> assertThat(a.getBandwidthMbps()).as("check bandwidthMbps").isEqualTo(expected.getBandwidthMbps()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTopologyLinkUpdatableRelationshipsEquals(TopologyLink expected, TopologyLink actual) {
        assertThat(actual)
            .as("Verify TopologyLink relationships")
            .satisfies(a -> assertThat(a.getSourceDevice()).as("check sourceDevice").isEqualTo(expected.getSourceDevice()))
            .satisfies(a -> assertThat(a.getTargetDevice()).as("check targetDevice").isEqualTo(expected.getTargetDevice()));
    }
}
